languages = {
    0: {
        "button_stop": "Stop",
        "button_ready": "Ready",
        "button_reset": "Reset",
        "button_play": "Play",
        "button_force": "FORCE STOP",
        "button_start_rec": "Start Recording",
        "button_stop_rec": "Stop Recording",
        "page_main": "Home",
        "page_1": "Select",
        "page_2": "Upload",
        "page_3": "Record",
        "select_lang": "Language:",
        "select_song": "Select song:",
        "select_chord": "Adjust the basic chord of the song:",
        "list_song": "Available song",
        "result_chord": "Basic chord:",
        "upload_song": "Choose a file",
        "toast_ready": "Ready",
        "toast_reset": "Reset Success",
        "toast_stop": "Stopped",
        "toast_force": "FORCE STOPPED",
    },
    1: {
        "button_stop": "Berhenti",
        "button_ready": "Siap",
        "button_reset": "Atur Ulang",
        "button_play": "Putar Lagu",
        "button_force": "PAKSA BERHENTI",
        "button_start_rec": "Mulai Merekam",
        "button_stop_rec": "Berhenti Merekam",
        "page_main": "Beranda",
        "page_1": "Pilih Lagu",
        "page_2": "Unggah",
        "page_3": "Rekam",
        "select_lang": "Bahasa:",
        "select_song": "Pilih lagu:",
        "select_chord": "Sesuaikan nada dasar lagu:",
        "list_song": "Lagu yang tersedia",
        "result_chord": "Nada dasar:",
        "upload_song": "Pilih sebuah file",
        "toast_ready": "Siap",
        "toast_reset": "Atur Ulang Berhasil",
        "toast_stop": "Dihentikan",
        "toast_force": "PAKSA BERHENTI",
    },
}